### ISSUE TITLE
Feature request: Convert to TypeScript

### ISSUE THREAD

**Issue by DaveOrDead** [kinde-oss/kinde-auth-pkce-js#29]
### Prerequisites

- [X] I have searched the repository’s issues and [Kinde community](https://thekindecommunity.slack.com/archives/C04K34HUV9B) to ensure my feature request isn’t a duplicate
- [X] I have read the [contributing guidelines](https://github.com/kinde-oss/.github/blob/489e2ca9c3307c2b2e098a885e22f2239116394a/CONTRIBUTING.md)
- [X] I agree to the terms in the [code of conduct](https://github.com/kinde-oss/.github/blob/489e2ca9c3307c2b2e098a885e22f2239116394a/CODE_OF_CONDUCT.md)

### What is the problem you’re trying to solve?

Feedback from the community is they would like a TS version of the SDK.

We currently expose all the types in a type definition file `index.d.ts`

### What solution would you like to see?

Conversion of library to TypeScript

**Comment by atifcppprogrammer** [comment]
Hey @DaveOrDead ! willing to pick this up next :smile:  please assign it to me

**Comment by DaveOrDead** [comment]
Awesome stuff, you're on fire! 🔥

**Comment by atifcppprogrammer** [comment]
Hey @DaveOrDead, sorry if this is taking a bit long, but I just wanted to let you know that I'll have a pull-request up for this, sometime this week :smile:

**Comment by DaveOrDead** [comment]
Champion - thanks @atifcppprogrammer!
