### ISSUE TITLE
Feature request: Provide an `isAuthenticated` method

### ISSUE THREAD

**Issue by DaveOrDead** [kinde-oss/kinde-auth-pkce-js#30]
### Prerequisites

- [X] I have searched the repository’s issues and [Kinde community](https://thekindecommunity.slack.com/archives/C04K34HUV9B) to ensure my feature request isn’t a duplicate
- [X] I have read the [contributing guidelines](https://github.com/kinde-oss/.github/blob/489e2ca9c3307c2b2e098a885e22f2239116394a/CONTRIBUTING.md)
- [X] I agree to the terms in the [code of conduct](https://github.com/kinde-oss/.github/blob/489e2ca9c3307c2b2e098a885e22f2239116394a/CODE_OF_CONDUCT.md)

### What is the problem you’re trying to solve?

Several of the other Kinde SDKs offer an `isAuthenticated` method to improve the developer experience of checking if a user is authenticated

### What solution would you like to see?

Add an `isAuthenticated` method to the library

**Comment by atifcppprogrammer** [comment]
Hey @DaveOrDead I'd like a crack at this please assign this issue to me, just curious about one thing though, should the `isAuthenticated` method simply check if the user is authenticated i.e. the access token in memory is not yet expired or should it also attempt an initial refresh of the access token if it is expired. The **kinde-nodejs-sdk** for example does perform an initial refresh if the access token is expired as you can see [**here**](https://github.com/kinde-oss/kinde-nodejs-sdk/blob/main/src/KindeClient.js#L456C8-L456C8).

**Comment by DaveOrDead** [comment]
Hey @atifcppprogrammer , thanks for picking this up :) 

Attempting an initial refresh sounds like a great enhancement if you're keen for it
