### ISSUE TITLE
Bug: KindeClient methods require arguments that are in fact optional

### ISSUE THREAD

**Issue by marcosmartini** [kinde-oss/kinde-auth-pkce-js#53]
### Prerequisites

- [X] I have searched the repository’s issues and [Kinde community](https://thekindecommunity.slack.com/archives/C04K316BXEH) to ensure my issue isn’t a duplicate
- [X] I have checked the latest version of the library to replicate my issue
- [X] I have read the [contributing guidelines](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/main/.github/CODE_OF_CONDUCT.md)

### Describe the issue

The `login`, `register`, and `createOrg` methods in the [KindeClient](https://github.com/kinde-oss/kinde-auth-pkce-js/blob/01397e6b8caa88802f86fc9983f9cd9bfce0184c/src/types.ts#L96C13-L96C24) type are currently making the `options` argument required. When looking at `AuthOptions` and `OrgOptions`, both types are fully optional. Fixing these will stop TypeScript errors showing up when using this library within a TypeScript project.

### Library URL

https://github.com/kinde-oss/kinde-auth-pkce-js

### Library version

3.0.25

### Operating system(s)

macOS

### Operating system version(s)

macOS Sonoma 14.1

**Comment by DaveOrDead** [comment]
Cheers @marcosmartini 🚀
